! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use bad_test, only: &
                bad_is_leap_year => test_is_leap_year
        use fancy_test, only: &
                fancy_is_leap_year => test_is_leap_year
        use good_test, only: &
                good_is_leap_year => test_is_leap_year
        use ugly_test, only: &
                ugly_is_leap_year => test_is_leap_year
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(4)

        individual_tests(1) = bad_is_leap_year()
        individual_tests(2) = fancy_is_leap_year()
        individual_tests(3) = good_is_leap_year()
        individual_tests(4) = ugly_is_leap_year()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
